### ISSUE TITLE
Adding calibration ?

### ISSUE THREAD

**Issue by Testato** [Grumbel/evtest-qt#4]
Hi,
all your tool is very good, 
evtest also is very useful but it is not possible calibrate a joystick.
Is it possible extend it functionalities for calibrate a joystick when it is present in the event list ?

There is some tool for calibrate joystick, and your tool jstest-gtk is the best, but it do not work on games that use SDL.
There is only a cli command that can manually calibrate an event driven joystick, but have an automatic calibration via a Gui should be the best (by extend functionalities of evtest-qt or by adding event calibration on jstest-gtk)

**Comment by Grumbel** [comment]
The `/dev/input/eventX` interface does not have calibration functionality like the old `/dev/input/jsX`, so there is nothing I can do.

Forcing SDL to use the old joystick interface might however still be possible via the environment variable `SDL_JOYSTICK_DEVICE=/dev/input/js0` (haven't tested it, not sure if it's still working in modern SDL2).
