### ISSUE TITLE
port to qt5

### ISSUE THREAD

**Issue by johndoe71rus** [Grumbel/evtest-qt#6]
qt4 is deprecated.
i get config error 

`CMake Error at /usr/share/cmake/Modules/FindQt4.cmake:1328 (message):
  Found unsuitable Qt version "5.11.1" from /usr/bin/qmake, this code
  requires Qt 4.x`
so what about move to qt5?

**Comment by Grumbel** [comment]
Already there:

 `cmake -DUSE_QT5=ON`

Should probably make that automatic based on failure of the Qt4 check.

**Comment by Grumbel** [comment]
Fixed in 0e54ae0
